{% set name = "types-chardet" %}
{% set version = "5.0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-chardet-{{ version }}.tar.gz
  sha256: 5692bfc24b23f2998d7f13cd0a73c520865db91e4eada42e6a572df0cf3f472c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/chardet-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for chardet
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
