{% set name = "types-chardet" %}
{% set version = "5.0.4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-chardet-{{ version }}.tar.gz
  sha256: caf4c74cd13ccfd8b3313c314aba943b159de562a2573ed03137402b2bb37818

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/chardet-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for chardet
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
